name: GitHubPagesForGAP
version: 0.2
date: 04/02/2017
description: |
    A GitHub Pages generator for GAP packages

authors:
    - name: Max Horn
      url: http://www.quendi.de/math
    - name: A. U. Thor

maintainers:
    - name: Max Horn
      url: http://www.quendi.de/math
    - name: Jan Itor

GAP: ">=4.8.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.2"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.1"
      url: "https://gap-packages.github.io/io"

suggested-pkgs:
    - name: "orb"
      version: ">= 4.2"
      url: "https://gap-packages.github.io/orb"

www: https://fingolfin.github.io/GitHubPagesForGAP/
readme: README.md
packageinfo: https://fingolfin.github.io/GitHubPagesForGAP/PackageInfo.g
github: https://github.com/fingolfin/GitHubPagesForGAP

downloads:
    - name: .tar.gz
      url: https://github.com/fingolfin/GitHubPagesForGAP/releases/download/v0.2/GitHubPagesForGAP-0.2.tar.gz
    - name: .tar.bz2
      url: https://github.com/fingolfin/GitHubPagesForGAP/releases/download/v0.2/GitHubPagesForGAP-0.2.tar.bz2

abstract: |
    This is a pseudo package that contains no actual  <span class="pkgname">GAP</span> code. Instead, it is a template for other  GAP packages that allows to quickly setup GitHub Pages.

status: other
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
