name: ModularGroup
version: "2.0.1"
license: "GPL-3.0-or-later"
date: 2026-04-22
description: |
    Finite-index subgroups of (P)SL(2,Integers)

authors:
    - name: Sebastian Engelhardt
      url: https://www.uni-saarland.de/lehrstuhl/weitze-schmithuesen.html
    - name: Luca Leon Junk
      url: https://www.uni-saarland.de/lehrstuhl/weber-moritz/team/luca-junk.html
    - name: Hannah Wagmann
      url: https://www.uni-saarland.de/lehrstuhl/weitze-schmithuesen/team/hannah-wagmann.html
    - name: Gabriela Weitze-Schmithüsen
      url: https://www.uni-saarland.de/lehrstuhl/weitze-schmithuesen/team/gabriela-weitze-schmithuesen.html

maintainers:
    - name: Sebastian Engelhardt
      url: https://www.uni-saarland.de/lehrstuhl/weitze-schmithuesen.html
    - name: Hannah Wagmann
      url: https://www.uni-saarland.de/lehrstuhl/weitze-schmithuesen/team/hannah-wagmann.html
    - name: Gabriela Weitze-Schmithüsen
      url: https://www.uni-saarland.de/lehrstuhl/weitze-schmithuesen/team/gabriela-weitze-schmithuesen.html

GAP: "4.12"

needed-pkgs:
    - name: "CTblLib"
      version: ">= 1.2.2"
      url: "https://www.math.rwth-aachen.de/~Thomas.Breuer/ctbllib"
    - name: "Congruence"
      version: ">=1.1.1"
      url: "https://gap-packages.github.io/congruence"

www: https://ag-weitze-schmithusen.github.io/ModularGroup
readme: README.md
packageinfo: https://ag-weitze-schmithusen.github.io/ModularGroup/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/ag-weitze-schmithusen/ModularGroup/releases/download/v2.0.1/ModularGroup-2.0.1.tar.gz

abstract: |
    This package provides a collection of algorithms for computing with   finite-index subgroups of (P)SL(2,Z).

status: other
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    PSL(2,Z), PSL2Z, SL(2,Z), SL2Z, modular group, congruence subgroup.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>EJWW26</span>]   <b class='BibAuthor'>Engelhardt, S., Junk, L. L., Wagmann, H. and Weitze-Schmithüsen, G.</b>,
     <i class='BibTitle'>ModularGroup, Finite-index subgroups of (P)SL(2,Integers),
             Version 2.0.1</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://ag-weitze-schmithusen.github.io/ModularGroup">https://ag-weitze-schmithusen.github.io/ModularGroup</a></span>.
    </p>
    

bibtex: |
    @misc{ ModularGroup,
      author =           {Engelhardt,  S.  and  Junk,  L. L. and Wagmann, H. and
                          Weitze\texttt{\symbol{45}}Schmith{\"u}sen, G.},
      title =            {{ModularGroup},       {Finite\texttt{\symbol{45}}index
                          subgroups of (P)SL(2,Integers)}, {V}ersion 2.0.1},
      month =            {Apr},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href
                          {https://ag-weitze-schmithusen.github.io/ModularGroup}
                          {\texttt{https://ag\texttt{\symbol{45}}weitze\texttt{\symbol{45}}schmithusen.github.io/}\discretionary
                          {}{}{}\texttt{ModularGroup}}},
      keywords =         {PSL(2,Z);   PSL2Z;   SL(2,Z);   SL2Z;  modular  group;
                          congruence subgroup},
      printedkey =       {EJWW26}
    }

