DeclareCategory("IsProjectiveModularSubgroup", IsFinitelyGeneratedGroup);
DeclareRepresentation("IsProjectiveModularSubgroupRepresentation", IsComponentObjectRep, ["s", "t"]);
DeclareSynonym("IsDefaultProjectiveModularSubgroup", IsProjectiveModularSubgroup and IsProjectiveModularSubgroupRepresentation);


DeclareAttribute("Index", IsProjectiveModularSubgroup);
DeclareAttribute("IsCongruence", IsProjectiveModularSubgroup);
DeclareAttribute("Cusps", IsProjectiveModularSubgroup);
DeclareAttribute("RightCosetRepresentatives", IsProjectiveModularSubgroup);
DeclareAttribute("LeftCosetRepresentatives", IsProjectiveModularSubgroup);
DeclareAttribute("GeneralizedLevel", IsProjectiveModularSubgroup);
DeclareAttribute("GeneratorsOfGroup", IsProjectiveModularSubgroup);
DeclareAttribute("WordGeneratorsOfGroup", IsProjectiveModularSubgroup);
DeclareAttribute("NormalCore", IsProjectiveModularSubgroup);
DeclareAttribute("QuotientByNormalCore", IsProjectiveModularSubgroup);
DeclareAttribute("AssociatedCharacterTable", IsProjectiveModularSubgroup);
DeclareAttribute("Genus", IsProjectiveModularSubgroup);
DeclareAttribute("Deficiency", IsProjectiveModularSubgroup);

DeclareOperation("DefinesProjectiveCosetAction", [IsPerm, IsPerm]);
DeclareOperation("ProjectiveModularSubgroup", [IsPerm, IsPerm]);
DeclareOperation("ProjectiveModularSubgroupViaRightAction", [IsPerm, IsPerm]);
DeclareOperation("ProjectiveModularSubgroupViaLeftAction", [IsPerm, IsPerm]);
DeclareOperation("SAction", [IsProjectiveModularSubgroup]);
DeclareOperation("SRightAction", [IsProjectiveModularSubgroup]);
DeclareOperation("SLeftAction", [IsProjectiveModularSubgroup]);
DeclareOperation("TAction", [IsProjectiveModularSubgroup]);
DeclareOperation("TRightAction", [IsProjectiveModularSubgroup]);
DeclareOperation("TLeftAction", [IsProjectiveModularSubgroup]);
DeclareOperation("CosetActionOf", [IsMatrix, IsProjectiveModularSubgroup]);
DeclareOperation("CosetRightActionOf", [IsMatrix, IsProjectiveModularSubgroup]);
DeclareOperation("CosetLeftActionOf", [IsMatrix, IsProjectiveModularSubgroup]);
DeclareOperation("IsElementOf", [IsMatrix, IsProjectiveModularSubgroup]);
DeclareOperation("IsWordElementOf", [IsElementOfFpGroup, IsProjectiveModularSubgroup]);
DeclareOperation("IsWordElementOf", [IsString, IsProjectiveModularSubgroup]);
DeclareOperation("CuspWidth", [IsRat, IsProjectiveModularSubgroup]);
DeclareOperation("CuspsEquivalent", [IsRat, IsRat, IsProjectiveModularSubgroup]);
DeclareOperation("CosetRepresentativeOfCusp", [IsRat, IsProjectiveModularSubgroup]);
DeclareOperation("LiftToSL2ZEven", [IsProjectiveModularSubgroup]);
DeclareOperation("LiftToSL2ZOdd", [IsProjectiveModularSubgroup]);
DeclareOperation("IndexModN", [IsProjectiveModularSubgroup, IsPosInt]);
DeclareOperation("Deficiency", [IsProjectiveModularSubgroup, IsPosInt]);
DeclareOperation("Conjugate", [IsProjectiveModularSubgroup, IsMatrix]);
